parameters:
  versionSpec: "3.11.4"
  branch: ""
  zipBuildPrefix: ""
  buildCommand: ""
  skypBuildArtifact: '*/\.* *.git* *azure-pipelines.yml*'
  taskCustomIsEnabled: false
  taskCustom: ""
steps:
  - script: |
      BRANCH=`echo ${{ parameters.branch }} | cut -d "/" -f3`
      BUILDFILENAME="${BRANCH}_build${{ parameters.zipBuildPrefix }}"
      
      echo "##vso[task.setvariable variable=branch]$BRANCH"
      echo "##vso[task.setvariable variable=buildFileName]$BUILDFILENAME"
    displayName: "Prepare strategy"

  - task: UsePythonVersion@0
    inputs:
      versionSpec: ${{parameters.versionSpec}}  # Puedes especificar la versión de Python que deseas, como '3.8' o '3.x' para la última versión
      addToPath: true
    displayName: "Install Python"
      
  - script: ${{ parameters.buildCommand }}
    displayName: "Install dependencies and build"

  - script: |
      zip -rq $(buildFileName).zip . -x ${{parameters.skypBuildArtifact}}
    displayName: 'Generate "zip" of the build'

  - task: PublishBuildArtifacts@1
    displayName: 'Publish "zip" in Artifact'
    inputs:
      pathToPublish: "$(buildFileName).zip"
      artifactName: "$(branch)"